import './global.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { themeClass } from '@alpina/alpina-ui-kit';
export const metadata = {
  title: 'Welcome to alpina-web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={themeClass}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
